theme = "nord"

[editor]
line-number = "absolute"
bufferline = "multiple"
auto-pairs = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false